In [24]:
import time
import cvxpy
import random
import numpy as np
import pandas as pd

In [25]:
# サンプルデータの読み込み
sample = pd.read_csv('sample_10*5000.csv')

In [26]:
sample.head(3)

,id,price_A,price_B,price_C,price_D,price_E,price_F,price_G,price_H,price_I,...,rating_A,rating_B,rating_C,rating_D,rating_E,rating_F,rating_G,rating_H,rating_I,rating_J
0,1,380,385,389,375,387,385,382,378,385,...,4.1,3.3,4.0,3.5,3.8,4.5,4.1,3.8,3.8,3.8
1,2,943,947,961,960,960,947,950,940,944,...,10.1,8.9,9.3,10.3,9.4,9.5,9.9,9.4,8.4,9.1
2,3,980,980,987,982,974,982,981,982,975,...,10.4,8.7,10.3,9.8,9.3,9.0,9.8,9.8,9.8,9.8

In [27]:
sample = sample[:800]

In [28]:
# クライアトa, b, cの元々持っていた枠をランダムに決める。
length = len(sample) #dfの長さ。
ids = list(range(length)) #「0~length-1」の数字の列。
client_num = int((len(sample.columns)-1)/2) # (カラムの数-1('id'))/2

# idは1からなので、1を足す。
random_ids = [id+1 for id in ids]

# Break point.
bp1 = length//client_num 
bp2 = length//client_num + bp1
bp3 = length//client_num + bp2
bp4 = length//client_num + bp3
bp5 = length//client_num + bp4
bp6 = length//client_num + bp5
bp7 = length//client_num + bp6
bp8 = length//client_num + bp7
bp9 = length//client_num + bp8

# 順番シャッフルして、Break pointで切り分ける。
random.shuffle(random_ids)

id_A = random_ids[:bp1]
id_B = random_ids[bp1:bp2]
id_C = random_ids[bp2:bp3]
id_D = random_ids[bp3:bp4]
id_E = random_ids[bp4:bp5]
id_F = random_ids[bp5:bp6]
id_G = random_ids[bp6:bp7]
id_H = random_ids[bp7:bp8]
id_I = random_ids[bp8:bp9]
id_J = random_ids[bp9:]

In [29]:
# それぞれのidを表示。 ランダムにシャッフルされていることがわかる。
print(len(id_A),len(id_B),len(id_C),len(id_D),len(id_E),
     len(id_F),len(id_G),len(id_H),len(id_I),len(id_J),)
print(id_A[:10])

80 80 80 80 80 80 80 80 80 80
[388, 134, 526, 117, 552, 484, 587, 300, 93, 132]

In [30]:
# それぞれのidのデータのみを取り出すための判別用カラム。
sample['judge_A'] = sample['id'].apply(lambda x:x in id_A)
sample['judge_B'] = sample['id'].apply(lambda x:x in id_B)
sample['judge_C'] = sample['id'].apply(lambda x:x in id_C)
sample['judge_D'] = sample['id'].apply(lambda x:x in id_D)
sample['judge_E'] = sample['id'].apply(lambda x:x in id_E)
sample['judge_F'] = sample['id'].apply(lambda x:x in id_F)
sample['judge_G'] = sample['id'].apply(lambda x:x in id_G)
sample['judge_H'] = sample['id'].apply(lambda x:x in id_H)
sample['judge_I'] = sample['id'].apply(lambda x:x in id_I)
sample['judge_J'] = sample['id'].apply(lambda x:x in id_J)

In [31]:
# それぞれのidのデータを取得。
df_A = sample[sample['judge_A']].loc[:, ['id','price_A', 'rating_A']]
df_B = sample[sample['judge_B']].loc[:, ['id','price_B', 'rating_B']]
df_C = sample[sample['judge_C']].loc[:, ['id','price_C', 'rating_C']]
df_D = sample[sample['judge_D']].loc[:, ['id','price_D', 'rating_D']]
df_E = sample[sample['judge_E']].loc[:, ['id','price_E', 'rating_E']]
df_F = sample[sample['judge_F']].loc[:, ['id','price_F', 'rating_F']]
df_G = sample[sample['judge_G']].loc[:, ['id','price_G', 'rating_G']]
df_H = sample[sample['judge_H']].loc[:, ['id','price_H', 'rating_H']]
df_I = sample[sample['judge_I']].loc[:, ['id','price_I', 'rating_I']]
df_J = sample[sample['judge_J']].loc[:, ['id','price_J', 'rating_J']]

In [32]:
# 判別用カラムを削除。
del sample['judge_A']
del sample['judge_B']
del sample['judge_C']
del sample['judge_D']
del sample['judge_E']
del sample['judge_F']
del sample['judge_G']
del sample['judge_H']
del sample['judge_I']
del sample['judge_J']

In [33]:
# 元々の値段の総和、元々の視聴率の和を計算する。
# Original price, Original point
original_price_A, original_point_A = sum(df_A['price_A']), sum(df_A['rating_A'])
original_price_B, original_point_B = sum(df_B['price_B']), sum(df_B['rating_B'])
original_price_C, original_point_C = sum(df_C['price_C']), sum(df_C['rating_C'])
original_price_D, original_point_D = sum(df_D['price_D']), sum(df_D['rating_D'])
original_price_E, original_point_E = sum(df_E['price_E']), sum(df_E['rating_E'])
original_price_F, original_point_F = sum(df_F['price_F']), sum(df_F['rating_F'])
original_price_G, original_point_G = sum(df_G['price_G']), sum(df_G['rating_G'])
original_price_H, original_point_H = sum(df_H['price_H']), sum(df_H['rating_H'])
original_price_I, original_point_I = sum(df_I['price_I']), sum(df_I['rating_I'])
original_price_J, original_point_J = sum(df_J['price_J']), sum(df_J['rating_J'])

In [34]:
# 各クライアントの考える価値（指定視聴率/値段）を数値化し、表に加える。
# 指定した視聴率/そのクライアントの号数価格
sample['value_A'] = round((sample['rating_A']/sample['price_A'])*1000, 2)
sample['value_B'] = round((sample['rating_B']/sample['price_B'])*1000, 2)
sample['value_C'] = round((sample['rating_C']/sample['price_C'])*1000, 2)
sample['value_D'] = round((sample['rating_D']/sample['price_D'])*1000, 2)
sample['value_E'] = round((sample['rating_E']/sample['price_E'])*1000, 2)
sample['value_F'] = round((sample['rating_F']/sample['price_F'])*1000, 2)
sample['value_G'] = round((sample['rating_G']/sample['price_G'])*1000, 2)
sample['value_H'] = round((sample['rating_H']/sample['price_H'])*1000, 2)
sample['value_I'] = round((sample['rating_I']/sample['price_I'])*1000, 2)
sample['value_J'] = round((sample['rating_J']/sample['price_J'])*1000, 2)

In [35]:
print('client_Aの交換前の合計価格:', original_price_A, 'client_Aの交換前の合計視聴率', round(original_point_A, 1))
print('client_Bの交換前の合計価格:', original_price_B, 'client_Bの交換前の合計視聴率', round(original_point_B, 1))
print('client_Cの交換前の合計価格:', original_price_C, 'client_Cの交換前の合計視聴率', round(original_point_C, 1))
print('client_Dの交換前の合計価格:', original_price_D, 'client_Dの交換前の合計視聴率', round(original_point_D, 1))
print('client_Eの交換前の合計価格:', original_price_E, 'client_Eの交換前の合計視聴率', round(original_point_E, 1))
print('client_Fの交換前の合計価格:', original_price_F, 'client_Fの交換前の合計視聴率', round(original_point_F, 1))
print('client_Gの交換前の合計価格:', original_price_G, 'client_Gの交換前の合計視聴率', round(original_point_G, 1))
print('client_Hの交換前の合計価格:', original_price_H, 'client_Hの交換前の合計視聴率', round(original_point_H, 1))
print('client_Iの交換前の合計価格:', original_price_I, 'client_Iの交換前の合計視聴率', round(original_point_I, 1))
print('client_Jの交換前の合計価格:', original_price_J, 'client_Jの交換前の合計視聴率', round(original_point_J, 1))

sample.head(3)

client_Aの交換前の合計価格: 66678 client_Aの交換前の合計視聴率 661.4
client_Bの交換前の合計価格: 66863 client_Bの交換前の合計視聴率 667.2
client_Cの交換前の合計価格: 62790 client_Cの交換前の合計視聴率 627.4
client_Dの交換前の合計価格: 69178 client_Dの交換前の合計視聴率 691.6
client_Eの交換前の合計価格: 68366 client_Eの交換前の合計視聴率 684.8
client_Fの交換前の合計価格: 73696 client_Fの交換前の合計視聴率 736.4
client_Gの交換前の合計価格: 70145 client_Gの交換前の合計視聴率 700.7
client_Hの交換前の合計価格: 61532 client_Hの交換前の合計視聴率 608.0
client_Iの交換前の合計価格: 69145 client_Iの交換前の合計視聴率 695.6
client_Jの交換前の合計価格: 63481 client_Jの交換前の合計視聴率 622.9

,id,price_A,price_B,price_C,price_D,price_E,price_F,price_G,price_H,price_I,...,value_A,value_B,value_C,value_D,value_E,value_F,value_G,value_H,value_I,value_J
0,1,380,385,389,375,387,385,382,378,385,...,10.79,8.57,10.28,9.33,9.82,11.69,10.73,10.05,9.87,9.95
1,2,943,947,961,960,960,947,950,940,944,...,10.71,9.40,9.68,10.73,9.79,10.03,10.42,10.00,8.90,9.50
2,3,980,980,987,982,974,982,981,982,975,...,10.61,8.88,10.44,9.98,9.55,9.16,9.99,9.98,10.05,9.99

In [36]:
# 交換前のデータをまとめる。
original_prices = [original_price_A, original_price_B, original_price_C, original_price_D, original_price_E,
                   original_price_F, original_price_G, original_price_H, original_price_I, original_price_J]
original_points = [original_point_A, original_point_B, original_point_C, original_point_D, original_point_E,
                   original_point_F, original_point_G, original_point_H, original_point_I, original_point_J]

In [37]:
print(original_prices)
print(original_points)

[66678, 66863, 62790, 69178, 68366, 73696, 70145, 61532, 69145, 63481]
[661.4, 667.2000000000002, 627.4, 691.6000000000001, 684.8000000000002, 736.3999999999997, 700.7, 608.0000000000002, 695.5999999999999, 622.8999999999997]

<b><font color='Red'><font size=4>※valueは、正の数じゃないと、選ばなくなってしまうことに注意。<br>（０の方が大きいから。）</font></font></b>

***
***

### 〜ここからアルゴリズム〜

In [38]:
# ナップザック問題。

# size = 値段のデータ。
# weight = 価値のデータ。
# capacity = 元々の値段×1.05倍の値段。
# ids = 取得すべきだと考えられた枠のid    

def Knapsack(size, weight, capacity, obtained=0, rate=0.05):
    # 価格が元の価格の1.05%を超えても、終わり。
    if capacity*(1 + rate) - obtained > 0:        
        x = cvxpy.Variable(size.shape[0], boolean=True)
        # 要素の個数(これを加えて平均を最大化しないと、価格の小さいものばかりをとってしまう。)
        count = sum(np.ones(len(size)) * x)
        # 目的
        objective = cvxpy.Maximize(weight * x / count)
        # 制限。ここでは、capacity(元々の価格)の上下5%を取っている。obtainedを引くことで、ループを繰り返すことに対応。
        constraints = [capacity*(1 + rate) -  obtained >= size * x] 
        constraints += [capacity*(1 - rate) - obtained <= size * x]

        prob = cvxpy.Problem(objective, constraints)
        prob.solve(solver=cvxpy.ECOS_BB)
        result = [round(ix, 0) for ix in x.value]

        return result
    else:
        return []
    
# 2重のリストをフラットにする関数(重複は残る！)
def Flatten_dual(nested_list):
    return [e for inner_list in nested_list for e in inner_list]

In [39]:
# dfは、上記のsampleのような、カラム名がprice_A, rating_A, value_A, price_B, ...となっているDataFrame。
# namesには、'A', 'B', 'C', ... を入れるイメージ。

def Loop(df, original_prices, original_points, *names):
    result = dict() #結果を格納する。
    num = len(names) #クライアントの数。

    obtained_prices = [0 for i in range(num)] #獲得した枠の値段をそれぞれ格納する。
    obtained_points = [0 for i in range(num)] #獲得した枠の視聴率をそれぞれ格納する。
    obtained_idses = [[] for i in range(num)] #獲得した枠のidをそれぞれ格納する。
    idses = [[] for i in range(num)] # 各ナップザック問題でそれぞれが指定した枠のidを格納する。
    add_idses = [[] for i in range(num)] # 各ナップザック問題の結果、獲得した枠のidを格納する。
    check_point = 0
    
    while check_point==0: #何回ナップザックループを行うかわからないので、チェックポイントの値で判別する。
        for i in range(num): #それぞれのクライアントごと。
            original_price = original_prices[i] # 交換前の価格合計。
            original_point = original_points[i] # 交換前の視聴率合計。

            name = names[i] # クライアントの名前。
            size = np.array(df['price_' + name]) # dfのカラム名は、こうなるように指定。全ての枠の値段を取得。
            weight = np.array(df['value_' + name]) # dfのカラム名は、こうなるように指定。全ての枠の価値を取得。
            capacity = original_price 
            
            rate=0.05
            if obtained_points[i] < original_point: # 獲得した視聴率和が元々の視聴率和より低かったら
                for try_count in range(6): #5回までなら、rateを0.02ずつ大きくして試せる。
                    try:
                        idses[i] = Knapsack(size, weight, capacity,  obtained_prices[i], rate=rate)
                    except TypeError:
                        rate+=0.02
                    else: # エラーが発生しなかった時の処理。
                        break
                else: # リトライが全部失敗した時の処理。
                    idses[i] = [0 for i in range(len(size))] # rateが0.15を超えても無理なら、どのidも選択しない。            
            else:
                idses[i] = [0 for i in range(len(size))] # 視聴率和が元々の視聴率和を超えていた場合、どのidも選択しない。

        if sum(Flatten_dual(idses)) == 0: #もし、どのクライアントも選んでいなかったら
            idses[0][0] = 1 # 始めのクライアントがdfの一番上の行を選んだことにする。（暫定的なエラー処理。）
            
        ids = np.array(df['id'].index) + 1

        # それぞれの枠を選択したクライアントの中から１つをランダムに選択する。
        ids_dict = dict()
        for key in ids-1: # それぞれのidごとに、
            values = [] # そのidの枠を指定したクライアントを格納するリスト。
            for i in range(num): # それぞれのクライアントごとに、
                if key in idses[i] * ids -1: # そのid（のindex）があれば、
                    values.append(names[i]) # valuesにクライアントの名前が格納される。
            if values: # そのidを指定したクライアントがいれば、
                value = random.choice(values) # その中からクライアントをランダムに選ぶ。
                ids_dict[key] = value # idと合わせて格納される。

        for i in range(num):
            add_idses[i] = [ids for ids, client in ids_dict.items() if client == names[i]] # クライアントごとに、獲得したid
            # obtained_idses[i] += add_idses[i]
            obtained_idses[i] += df.query('index in ' + str(add_idses[i]))['id'].values.tolist()
            obtained_prices[i] += sum(df.query('index in ' + str(add_idses[i]))['price_' + name])
            obtained_points[i] += sum(df.query('index in ' + str(add_idses[i]))['rating_' + name])

        extraction_ids = Flatten_dual(add_idses) # 今回獲得されたidの集合を、取り除く。
        df = df.query('index not in ' + str(extraction_ids)).reset_index(drop=True)
        
        if len(df) == 1 and df['id'][0] != 0: #dfの長さが１だとうまく機能しないため、長さが１の場合は加える。
            add_df = pd.DataFrame(np.zeros(df.shape[1])).T # np.zeros()の中の数字は、列の数。
            add_df.columns = df.columns # カラム名を揃える。
            df = pd.concat([df, add_df]).reset_index(drop=True)

        # 上のプログラムの後にデータフレームの長さが1(=add_dfしか残っていない)なら、終了！！
        if len(df) <= 1:
            check_point += 1
    
    if obtained_points > original_points:
        sum_point = round(sum(obtained_points), 2) # 合計値を小数第二位までで表示。
        result[sum_point] = obtained_prices, obtained_idses
                                  
    return result

In [40]:
# 1回のループの結果。
# ちなみに、横に並べられるリストの要素数の上限は20なので、20を越えると縦に並び始める。
start = time.time()
result = Loop(sample, original_prices, original_points, 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J')
end = time.time()
print('処理時間は:', round(end-start, 3), '[sec]')
result

処理時間は: 328.169 [sec]

{6742.5: ([80524.0,
   65070,
   59676,
   65730,
   64955,
   70863,
   73648,
   64578,
   65699,
   61263],
  [[289,
    327,
    385,
    81,
    267,
    414,
    98,
    308,
    416,
    443,
    502,
    50,
    90,
    292,
    627,
    631,
    644,
    660,
    795,
    67,
    127,
    296,
    576,
    153,
    331,
    482,
    300,
    361,
    388,
    457,
    464,
    524,
    799,
    544,
    635,
    702,
    773,
    291,
    428,
    767,
    446,
    451,
    575,
    711,
    299,
    338,
    516,
    587,
    657,
    787,
    19,
    169,
    246,
    688,
    765,
    27,
    122,
    150,
    158,
    162,
    245,
    465,
    514,
    759,
    166,
    284,
    413,
    647,
    4,
    5,
    6,
    15,
    16,
    22,
    38,
    46,
    55,
    73,
    76,
    83,
    91,
    120,
    123,
    140,
    141,
    159,
    163,
    178,
    198,
    202,
    207,
    211,
    223,
    237,
    238,
    261,
    276,
    277,
    286,
    287,
    311,
    314,
    325,
    330,
    332,
    339,
    347,
    350,
    356,
    365,
    368,
    375,
    378,
    379,
    382,
    384,
    407,
    438,
    445,
    450,
    453,
    459,
    460,
    467,
    468,
    483,
    486,
    489,
    491,
    503,
    504,
    505,
    506,
    526,
    530,
    533,
    538,
    545,
    546,
    562,
    567,
    571,
    624.0],
   [195,
    371,
    390,
    454,
    717,
    101,
    145,
    148,
    399,
    496,
    678,
    435,
    523,
    597,
    752,
    342,
    406,
    784,
    279,
    404,
    612,
    126,
    230,
    461,
    703,
    705,
    763,
    779,
    367,
    412,
    474,
    515,
    751,
    2,
    107,
    499,
    602,
    726,
    43,
    79,
    85,
    132,
    255,
    554,
    721,
    775,
    466,
    494,
    762,
    7,
    727,
    113,
    146,
    273,
    381,
    532,
    88,
    128,
    301,
    615,
    250,
    293,
    377,
    417,
    552,
    643,
    757],
   [131,
    208,
    234,
    595,
    171,
    298,
    376,
    429,
    444,
    458,
    478,
    553,
    333,
    695,
    176,
    564,
    697,
    111,
    242,
    539,
    669,
    201,
    405,
    655,
    725,
    56,
    231,
    321,
    391,
    436,
    48,
    228,
    263,
    112,
    481,
    584,
    36,
    154,
    380,
    673,
    771,
    271,
    434,
    743,
    791,
    26,
    247,
    540,
    633,
    708,
    531,
    94,
    626,
    418,
    563,
    18,
    253,
    550,
    583,
    737,
    1,
    315,
    473,
    748,
    295],
   [366,
    105,
    144,
    218,
    254,
    260,
    305,
    535,
    543,
    630,
    110,
    264,
    565,
    730,
    51,
    77,
    96,
    194,
    283,
    495,
    578,
    47,
    164,
    189,
    31,
    64,
    354,
    369,
    439,
    792,
    135,
    180,
    411,
    581,
    70,
    217,
    236,
    334,
    363,
    724,
    316,
    603,
    674,
    34,
    99,
    790,
    75,
    423,
    610,
    317,
    393,
    549,
    586,
    13,
    161,
    244,
    680,
    731,
    103,
    142,
    306,
    322,
    432,
    557,
    558,
    712,
    222,
    649,
    469],
   [80,
    225,
    304,
    307,
    397,
    174,
    425,
    484,
    66,
    86,
    197,
    297,
    313,
    337,
    768,
    794,
    294,
    573,
    671,
    715,
    753,
    340,
    386,
    485,
    561,
    613,
    720,
    599,
    729,
    320,
    352,
    760,
    60,
    71,
    168,
    501,
    419,
    170,
    248,
    346,
    772,
    8,
    78,
    199,
    266,
    410,
    447,
    534,
    713,
    739,
    11,
    437,
    551,
    728,
    734,
    95,
    106,
    252,
    69,
    351,
    100,
    204,
    580,
    619,
    124,
    214,
    750,
    723],
   [97,
    216,
    281,
    395,
    480,
    519,
    547,
    556,
    585,
    682,
    786,
    119,
    676,
    766,
    54,
    129,
    257,
    490,
    598,
    29,
    220,
    259,
    274,
    324,
    470,
    661,
    741,
    41,
    312,
    663,
    677,
    694,
    761,
    109,
    387,
    588,
    592,
    798,
    175,
    422,
    542,
    637,
    93,
    686,
    758,
    789,
    125,
    498,
    555,
    205,
    357,
    517,
    84,
    475,
    520,
    137,
    280,
    355,
    359,
    402,
    57,
    268,
    409,
    492,
    691,
    20,
    58,
    288,
    408,
    683],
   [72,
    138,
    165,
    398,
    400,
    449,
    608,
    670,
    738,
    28,
    173,
    487,
    667,
    186,
    193,
    622,
    732,
    102,
    167,
    212,
    226,
    343,
    362,
    477,
    628,
    770,
    782,
    488,
    521,
    658,
    672,
    302,
    373,
    426,
    21,
    235,
    389,
    800,
    12,
    462,
    53,
    181,
    456,
    560,
    49,
    206,
    529,
    690,
    472,
    710,
    742,
    756,
    30,
    616,
    39,
    87,
    160,
    510,
    596,
    115,
    149,
    243,
    527,
    569,
    735,
    778,
    203,
    209,
    240,
    500,
    601,
    719,
    210,
    681,
    572,
    590,
    600,
    606,
    621,
    623,
    632,
    640,
    652,
    653,
    654,
    685,
    693,
    696,
    698,
    701,
    704,
    716,
    718,
    722,
    736,
    740,
    746,
    749,
    774,
    776,
    785,
    797],
   [52,
    265,
    607,
    618,
    666,
    781,
    370,
    392,
    617,
    769,
    42,
    215,
    232,
    497,
    512,
    589,
    594,
    642,
    364,
    605,
    675,
    777,
    309,
    611,
    745,
    3,
    221,
    421,
    383,
    239,
    424,
    537,
    33,
    157,
    130,
    196,
    336,
    401,
    706,
    62,
    269,
    548,
    629,
    35,
    319,
    353,
    394,
    764,
    63,
    139,
    152,
    733,
    241,
    318,
    328,
    358,
    59,
    104,
    566,
    620,
    684,
    689,
    755,
    10,
    23,
    68,
    156,
    188,
    213,
    249,
    272,
    326,
    344,
    345,
    360,
    433,
    508,
    574,
    577,
    641,
    679,
    754],
   [37,
    114,
    155,
    179,
    183,
    525,
    541,
    747,
    182,
    282,
    744,
    65,
    229,
    559,
    687,
    700,
    396,
    609,
    403,
    650,
    780,
    14,
    17,
    32,
    143,
    151,
    285,
    290,
    463,
    528,
    579,
    645,
    668,
    147,
    233,
    256,
    452,
    536,
    665,
    509,
    518,
    522,
    614,
    636,
    9,
    184,
    441,
    796,
    92,
    117,
    200,
    348,
    24,
    335,
    44,
    192,
    455,
    568,
    593,
    625,
    707,
    40,
    374,
    224,
    323,
    604,
    651,
    714],
   [45,
    341,
    476,
    513,
    646,
    74,
    82,
    89,
    116,
    136,
    227,
    659,
    793,
    187,
    372,
    440,
    639,
    278,
    511,
    415,
    448,
    471,
    788,
    121,
    303,
    493,
    709,
    349,
    420,
    648,
    656,
    699,
    262,
    427,
    431,
    507,
    638,
    692,
    172,
    430,
    442,
    664,
    177,
    329,
    25,
    108,
    118,
    185,
    251,
    258,
    570,
    219,
    270,
    582,
    662,
    134,
    191,
    634,
    310,
    275,
    591,
    61,
    133,
    190,
    479,
    783]])}

### これを何度も繰り返すことにより、resultに値を格納しまくる。

In [61]:
start = time.time()

results = {}
for i in range(10):
    results.update(Loop(sample, original_prices, original_points, 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'))

end = time.time()
print('10回分の処理時間は:', round(end-start, 3), '[sec]')

処理時間は: 63.519 [sec]

In [62]:
# それぞれのループごとの交換の結果。
results

{809.1: ([11755, 5889, 7642.0, 9035, 7282, 8400, 5377, 11201, 7341, 6831],
  [[97,
    77,
    17,
    90,
    21,
    48,
    75,
    94,
    1,
    4,
    5,
    6,
    10,
    15,
    16,
    20,
    23,
    46,
    55,
    58],
   [37, 28, 41, 60, 11, 38],
   [86, 29, 3, 34, 78, 84, 87, 27, 69, 76.0],
   [54, 65, 96, 2, 31, 32, 7, 62, 95],
   [74, 71, 43, 93, 12, 8, 36, 53],
   [80, 50, 79, 33, 85, 30, 88, 40, 57, 63, 100],
   [81, 56, 70, 92, 35, 39, 22],
   [45, 72, 82, 64, 67, 9, 13, 19, 24, 91, 59, 61, 68, 73, 83],
   [52, 89, 98, 42, 66, 18],
   [51, 47, 14, 99, 26, 49, 25, 44]])}

In [63]:
# 最も視聴率和を大きくした交換の仕方を求める。
print('交換後の価格:',results[max(results.keys())][0])
print('交換後のそれぞれの枠')
print('A:', results[max(results.keys())][1][0])
print('B:', results[max(results.keys())][1][1])
print('C:', results[max(results.keys())][1][2])
print('D:', results[max(results.keys())][1][3])
print('E:', results[max(results.keys())][1][4])
print('F:', results[max(results.keys())][1][5])
print('G:', results[max(results.keys())][1][6])
print('H:', results[max(results.keys())][1][7])
print('I:', results[max(results.keys())][1][8])
print('J:', results[max(results.keys())][1][9])

交換後の価格: [11755, 5889, 7642.0, 9035, 7282, 8400, 5377, 11201, 7341, 6831]
交換後のそれぞれの枠
A: [97, 77, 17, 90, 21, 48, 75, 94, 1, 4, 5, 6, 10, 15, 16, 20, 23, 46, 55, 58]
B: [37, 28, 41, 60, 11, 38]
C: [86, 29, 3, 34, 78, 84, 87, 27, 69, 76.0]
D: [54, 65, 96, 2, 31, 32, 7, 62, 95]
E: [74, 71, 43, 93, 12, 8, 36, 53]
F: [80, 50, 79, 33, 85, 30, 88, 40, 57, 63, 100]
G: [81, 56, 70, 92, 35, 39, 22]
H: [45, 72, 82, 64, 67, 9, 13, 19, 24, 91, 59, 61, 68, 73, 83]
I: [52, 89, 98, 42, 66, 18]
J: [51, 47, 14, 99, 26, 49, 25, 44]

<b><font size=4><font color='#113BC5'>この数（クライアントの数:10, 枠の数:1000↑）だと、やはり時間がかかりすぎる…。</font></font></b>